# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmoPageBuilderDev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programm',
            name='main_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
